# Generated by Django 2.2.4 on 2021-05-06 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aniolectivo',
            options={'verbose_name': 'Año lectivo', 'verbose_name_plural': 'Año lectivo'},
        ),
        migrations.RenameField(
            model_name='aniolectivo',
            old_name='id_cfg_estado',
            new_name='estado',
        ),
    ]
