# Generated by Django 2.2.4 on 2021-05-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matr', '0002_auto_20210506_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aniolectivo',
            name='anio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='aniolectivo',
            name='ciclo',
            field=models.IntegerField(),
        ),
    ]
