# Generated by Django 2.2.4 on 2021-05-07 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matr', '0004_auto_20210507_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabcurso',
            name='id_cfg_curso',
        ),
        migrations.AlterField(
            model_name='cabcurso',
            name='id_cfg_formacion',
            field=models.ForeignKey(db_column='id_cfg_formacion', on_delete=django.db.models.deletion.CASCADE, related_name='fk_cabcurso_formacion', to='cfg.GenrGeneral', verbose_name='Formación'),
        ),
        migrations.AlterField(
            model_name='cabcurso',
            name='id_cfg_modalidad',
            field=models.ForeignKey(db_column='id_cfg_modalidad', default=97, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cabcurso_modalidad', to='cfg.GenrGeneral', verbose_name='Modalidad'),
        ),
        migrations.AlterField(
            model_name='cabcurso',
            name='id_cfg_regimen',
            field=models.ForeignKey(db_column='id_cfg_regimen', default=97, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cabcurso_regimen', to='cfg.GenrGeneral', verbose_name='Regimen'),
        ),
        migrations.AlterField(
            model_name='cabcurso',
            name='id_cfg_tipo_edu',
            field=models.ForeignKey(db_column='id_cfg_tipo_educacion', on_delete=django.db.models.deletion.CASCADE, related_name='fk_materiaprof_tipoedu', to='cfg.GenrGeneral', verbose_name='Tipo de educación'),
        ),
    ]
