# Generated by Django 2.2.4 on 2021-05-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matr', '0007_auto_20210508_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='aniolectivo_curso',
            name='cupos',
            field=models.IntegerField(default=45),
        ),
    ]
