# Generated by Django 2.2.4 on 2021-05-08 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matr', '0008_aniolectivo_curso_cupos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallemateriacurso',
            name='id_cfg_materias',
        ),
        migrations.AddField(
            model_name='detallemateriacurso',
            name='id_materia',
            field=models.ForeignKey(db_column='id_materia', default=24, on_delete=django.db.models.deletion.CASCADE, related_name='fk_detallemateriacurso_materias', to='matr.Materia'),
        ),
    ]
