# Generated by Django 2.2.4 on 2021-05-11 18:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matr', '0010_auto_20210508_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia_profesor',
            name='dia_semana',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia_profesor',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora fin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='materia_profesor',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name='Hora de inicio'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='materia_profesor',
            name='id_detalle_materia_curso',
        ),
        migrations.AddField(
            model_name='materia_profesor',
            name='id_detalle_materia_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fk_materia_profesor', to='matr.DetalleMateriaCurso'),
            preserve_default=False,
        ),
    ]
