# Generated by Django 2.2.4 on 2021-05-16 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matr', '0011_auto_20210511_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemateriacurso',
            name='total_horas',
            field=models.TimeField(),
        ),
    ]
