# Generated by Django 2.2.4 on 2021-05-16 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('matr', '0012_auto_20210516_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallemateriacurso',
            name='total_horas',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
