# Generated by Django 2.2.4 on 2021-04-22 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenrGeneral',
            fields=[
                ('idgenr_general', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': ('Lista',),
                'verbose_name_plural': ('Listas',),
            },
        ),
        migrations.CreateModel(
            name='MensajePantalla',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('clave', models.CharField(max_length=50)),
                ('valor', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'MensajePantalla',
                'verbose_name_plural': 'MensajePantallas',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': ('Modulo',),
                'verbose_name_plural': ('Modulos',),
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfg.Modulo')),
                ('permiso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Permission')),
            ],
            options={
                'verbose_name': ('Menu',),
                'verbose_name_plural': ('Menus',),
            },
        ),
        migrations.CreateModel(
            name='GenrHistorial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('modulo', models.CharField(max_length=50)),
                ('accion', models.CharField(max_length=50)),
                ('usuario_mod', models.CharField(max_length=50)),
                ('terminal_mod', models.CharField(max_length=50)),
                ('fecha_mod', models.DateField()),
                ('id_menu', models.ForeignKey(db_column='id_menu', on_delete=django.db.models.deletion.CASCADE, related_name='fk_genrhistorial_confmenu', to='cfg.Menu')),
            ],
            options={
                'verbose_name': ('Historial',),
                'verbose_name_plural': ('Historiales',),
            },
        ),
    ]
