# Generated by Django 2.2.4 on 2021-04-22 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='icono',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
