# Generated by Django 2.2.4 on 2021-04-23 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0003_modulo_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='id_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfg.Modulo', verbose_name='Modulo'),
        ),
    ]
