# Generated by Django 2.2.4 on 2021-04-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0004_auto_20210423_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': ('Menu',), 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='modulo',
            options={'ordering': ['codigo'], 'verbose_name': ('Modulo',), 'verbose_name_plural': 'Modulos'},
        ),
        migrations.AddField(
            model_name='menu',
            name='url_menu',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
    ]
