# Generated by Django 2.2.4 on 2021-06-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfg', '0006_auto_20210424_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['nombre'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
    ]
