# Generated by Django 2.2.4 on 2021-04-22 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('identificacion', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.DateField(null=True)),
                ('lugar_nacimiento', models.CharField(max_length=45, null=True)),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('imagen', models.ImageField(default='../../../static/img/texto-menu.pnguser_default_image.svg', null=True, upload_to='static/usuarios/')),
                ('discapacidad', models.BooleanField(blank=True, null=True)),
                ('discapacidad_renal', models.BooleanField(blank=True, null=True)),
                ('discapacidad_neurologica', models.BooleanField(blank=True, null=True)),
                ('enfermedad_alergica', models.BooleanField(blank=True, null=True)),
                ('asma', models.BooleanField(blank=True, null=True)),
                ('epilepsia', models.BooleanField(blank=True, null=True)),
                ('enfermedad_congenita', models.BooleanField(blank=True, null=True)),
                ('enfermedad_respiratoria', models.BooleanField(blank=True, null=True)),
                ('atencion_psicologica', models.BooleanField(blank=True, null=True)),
                ('pnombres', models.CharField(blank=True, max_length=45, null=True)),
                ('papellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('pidentificacion', models.CharField(blank=True, max_length=15, null=True)),
                ('pdireccion', models.CharField(blank=True, max_length=45, null=True)),
                ('ptelefono', models.CharField(blank=True, max_length=45, null=True)),
                ('pvive_con_usted', models.BooleanField(blank=True, null=True)),
                ('mnombres', models.CharField(blank=True, max_length=45, null=True)),
                ('mapellidos', models.CharField(blank=True, max_length=45, null=True)),
                ('midentificacion', models.CharField(blank=True, max_length=15, null=True)),
                ('mdireccion', models.CharField(blank=True, max_length=45, null=True)),
                ('mtelefono', models.CharField(blank=True, max_length=45, null=True)),
                ('mvive_con_usted', models.BooleanField(blank=True, null=True)),
                ('bono_solidario', models.BooleanField(blank=True, null=True)),
                ('rnombres', models.CharField(blank=True, default='nombre representante', max_length=45, null=True)),
                ('rapellidos', models.CharField(blank=True, default='apellido representante', max_length=45, null=True)),
                ('rtelefono', models.CharField(blank=True, max_length=45, null=True)),
                ('ridentificacion', models.CharField(blank=True, max_length=13, null=True)),
                ('tipo_parentesco', models.CharField(blank=True, max_length=200, null=True)),
                ('rvive_con_usted', models.BooleanField(blank=True, null=True)),
                ('rdireccion_trabajo', models.CharField(blank=True, max_length=200, null=True)),
                ('rtelefono_trabajo', models.CharField(blank=True, max_length=20, null=True)),
                ('rcorreo', models.EmailField(max_length=50, null=True)),
                ('rhorario_laboral', models.CharField(blank=True, max_length=40, null=True)),
                ('mienbros_hogar', models.IntegerField(blank=True, null=True)),
                ('is_estudent', models.BooleanField(null=True)),
                ('is_empleado', models.BooleanField(null=True)),
                ('is_representante', models.BooleanField(null=True)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, null=True)),
                ('usuario_ing', models.CharField(max_length=45)),
                ('terminal_ing', models.CharField(max_length=105)),
                ('estado', models.ForeignKey(db_column='estado', default=97, on_delete=django.db.models.deletion.CASCADE, related_name='fk_persona_estado', to='cfg.GenrGeneral')),
                ('id_cfg_categoria_migratoria', models.ForeignKey(db_column='id_cfg_categoria_migratoria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_migratoria', to='cfg.GenrGeneral')),
                ('id_cfg_ciudad', models.ForeignKey(db_column='id_cfg_ciudad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='cfg.GenrGeneral')),
                ('id_cfg_estado_civil', models.ForeignKey(blank=True, db_column='id_cfg_estado_civil', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_civil', to='cfg.GenrGeneral')),
                ('id_cfg_estado_laboralm', models.ForeignKey(blank=True, db_column='id_cfg_estado_laboralm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_laboralm', to='cfg.GenrGeneral')),
                ('id_cfg_estado_laboralp', models.ForeignKey(db_column='id_cfg_estado_laboralp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_laboralp', to='cfg.GenrGeneral')),
                ('id_cfg_etnia', models.ForeignKey(db_column='id_cfg_etnia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etnia', to='cfg.GenrGeneral')),
                ('id_cfg_genero', models.ForeignKey(db_column='id_cfg_genero', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='cfg.GenrGeneral')),
                ('id_cfg_idioma_ancestral', models.ForeignKey(db_column='id_cfg_idioma_ancestral', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acestral', to='cfg.GenrGeneral')),
                ('id_cfg_indigena', models.ForeignKey(db_column='id_cfg_indigena', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indigena', to='cfg.GenrGeneral')),
                ('id_cfg_jornada', models.ForeignKey(db_column='id_cfg_jornada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jornada', to='cfg.GenrGeneral')),
                ('id_cfg_pais', models.ForeignKey(db_column='id_cfg_pais', null=True, on_delete=django.db.models.deletion.CASCADE, to='cfg.GenrGeneral')),
                ('id_cfg_provincia', models.ForeignKey(db_column='id_cfg_provincia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia', to='cfg.GenrGeneral')),
                ('id_cfg_tipo_identificacion', models.ForeignKey(db_column='id_cfg_tipo_identificacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identificacion', to='cfg.GenrGeneral')),
                ('id_cfg_tipo_sangre', models.ForeignKey(db_column='id_cfg_tipo_sangre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_de_sangre', to='cfg.GenrGeneral')),
                ('id_cfg_tipo_usuario', models.ForeignKey(db_column='id_cfg_tipo_usuario', default=19, on_delete=django.db.models.deletion.CASCADE, related_name='persona_tipo_usuario', to='cfg.GenrGeneral')),
                ('id_usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
