# Generated by Django 2.2.4 on 2021-04-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='is_estudent',
            new_name='is_estudiante',
        ),
        migrations.RenameField(
            model_name='persona',
            old_name='mienbros_hogar',
            new_name='miembros_hogar',
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mdireccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pdireccion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='terminal_ing',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='persona',
            name='usuario_ing',
            field=models.CharField(max_length=60),
        ),
    ]
