# Generated by Django 2.2.4 on 2021-04-25 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mant', '0002_auto_20210423_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='id_cfg_tipo_usuario',
        ),
        migrations.AlterField(
            model_name='persona',
            name='asma',
            field=models.BooleanField(blank=True, null=True, verbose_name='Asma'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='atencion_psicologica',
            field=models.BooleanField(blank=True, null=True, verbose_name='Necesita Atención psicológica'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='bono_solidario',
            field=models.BooleanField(blank=True, null=True, verbose_name='Representante recibe bono solidario'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='discapacidad',
            field=models.BooleanField(blank=True, null=True, verbose_name='Tiene alguna discapacidad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='discapacidad_neurologica',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padece de enfermedad neurológica'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='discapacidad_renal',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padece enfermedad renal'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='enfermedad_alergica',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padece de alergias'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='enfermedad_congenita',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padece enfermedad cognitiva'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='enfermedad_respiratoria',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padece enfermedad respiratoria'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='epilepsia',
            field=models.BooleanField(blank=True, null=True, verbose_name='Epilepsia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_categoria_migratoria',
            field=models.ForeignKey(db_column='id_cfg_categoria_migratoria', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_migratoria', to='cfg.GenrGeneral', verbose_name='Categoria migratoria'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_ciudad',
            field=models.ForeignKey(db_column='id_cfg_ciudad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad', to='cfg.GenrGeneral', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_estado_civil',
            field=models.ForeignKey(blank=True, db_column='id_cfg_estado_civil', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_civil', to='cfg.GenrGeneral', verbose_name='Estado civil'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_estado_laboralm',
            field=models.ForeignKey(blank=True, db_column='id_cfg_estado_laboralm', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_laboralm', to='cfg.GenrGeneral', verbose_name='Estado laboral de la madre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_estado_laboralp',
            field=models.ForeignKey(db_column='id_cfg_estado_laboralp', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estado_laboralp', to='cfg.GenrGeneral', verbose_name='Estado laboral del padre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_etnia',
            field=models.ForeignKey(db_column='id_cfg_etnia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etnia', to='cfg.GenrGeneral', verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_genero',
            field=models.ForeignKey(db_column='id_cfg_genero', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genero', to='cfg.GenrGeneral', verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_idioma_ancestral',
            field=models.ForeignKey(db_column='id_cfg_idioma_ancestral', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acestral', to='cfg.GenrGeneral', verbose_name='Idioma ancestral'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_indigena',
            field=models.ForeignKey(db_column='id_cfg_indigena', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indigena', to='cfg.GenrGeneral', verbose_name='Etnia indigena'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_jornada',
            field=models.ForeignKey(db_column='id_cfg_jornada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jornada', to='cfg.GenrGeneral', verbose_name='Joranda'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_pais',
            field=models.ForeignKey(db_column='id_cfg_pais', null=True, on_delete=django.db.models.deletion.CASCADE, to='cfg.GenrGeneral', verbose_name='Pais'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_provincia',
            field=models.ForeignKey(db_column='id_cfg_provincia', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provincia', to='cfg.GenrGeneral', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_tipo_identificacion',
            field=models.ForeignKey(db_column='id_cfg_tipo_identificacion', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identificacion', to='cfg.GenrGeneral', verbose_name='Tipo Identificación Representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='id_cfg_tipo_sangre',
            field=models.ForeignKey(db_column='id_cfg_tipo_sangre', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_de_sangre', to='cfg.GenrGeneral', verbose_name='Tipo de sangre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_empleado',
            field=models.BooleanField(null=True, verbose_name='Es Empleado'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_estudiante',
            field=models.BooleanField(null=True, verbose_name='Es Estudiante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='is_representante',
            field=models.BooleanField(null=True, verbose_name='Es Representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mapellidos',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Apellido de la madre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mdireccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección de la madre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='midentificacion',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Identificación de la madre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='miembros_hogar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero Miembros del hogar'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mnombres',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre de la madre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mtelefono',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Telefono de la madre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='mvive_con_usted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Madre vive con el estudiante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='papellidos',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Apellidos del padre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pdireccion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dirección del padre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pidentificacion',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Identificación del padre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pnombres',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombres del padre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ptelefono',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Telefono del padre'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='pvive_con_usted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Padre vive con el estudiante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rapellidos',
            field=models.CharField(blank=True, default='apellido representante', max_length=45, null=True, verbose_name='Apellido Representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rcorreo',
            field=models.EmailField(max_length=50, null=True, verbose_name='Correo Representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rdireccion_trabajo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección trabajo representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rhorario_laboral',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Horario Laboral'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='ridentificacion',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Identificación del Representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rnombres',
            field=models.CharField(blank=True, default='nombre representante', max_length=45, null=True, verbose_name='Nombre Representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rtelefono',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Telefono Representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rtelefono_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefono trabajo representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rvive_con_usted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Representante vive con el estudiante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_parentesco',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Parentesco'),
        ),
    ]
