# Generated by Django 2.2.4 on 2021-04-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant', '0003_auto_20210425_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='rapellidos',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Apellido Representante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rnombres',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Nombre Representante'),
        ),
    ]
