# Generated by Django 2.2.4 on 2021-04-28 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mant', '0004_auto_20210427_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='is_representante',
        ),
    ]
