# Generated by Django 2.2.4 on 2021-06-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mant', '0005_remove_persona_is_representante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['nombres']},
        ),
    ]
