# Generated by Django 2.2.4 on 2021-06-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mant', '0006_auto_20210610_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(default='static/dist/assets/images/faces/1.jpg', null=True, upload_to='static/usuarios/'),
        ),
    ]
